#!/bin/bash
# RDMA连接问题诊断脚本
# 用途：定位RDMA网线已插但link仍为down的问题

echo "============================================================"
echo "RDMA连接问题诊断方案"
echo "============================================================"
echo ""

echo "===== 步骤 1: 检查物理层 ====="
echo ""
echo "运行以下命令检查网口状态："
echo ""
echo "  # Server 1 (10.21.16.124)"
echo "  ssh sheng-xiang@10.21.16.124 'ethtool ens19f0np0 | grep -E Link'"
echo "  ssh sheng-xiang@10.21.16.124 'ethtool ens19f1np1 | grep -E Link'"
echo ""
echo "  # Server 2 (100.64.0.6)"
echo "  ssh sheng-xiang@100.64.0.6 'ethtool eno3np0 | grep -E Link'"
echo "  ssh sheng-xiang@100.64.0.6 'ethtool eno4np1 | grep -E Link'"
echo ""
echo "期望结果: Link detected: yes"
echo "当前结果: Link detected: no"
echo ""

echo "===== 步骤 2: 确认网线插的是哪个口 ====="
echo ""
echo "服务器可能有多个网口，请机房人员确认："
echo ""
echo "  Server 1 有这些RDMA网口:"
echo "    - ens19f0np0 (Mellanox ConnectX-5, PCIe slot 84:00.0)"
echo "    - ens19f1np1 (Mellanox ConnectX-5, PCIe slot 84:00.1)"
echo "  还有这些**非RDMA**网口:"
echo "    - ens20f1 (Intel X520 10GbE) ← 当前正在使用"
echo "    - ens24f0-ens24f3 (Intel I350 1GbE)"
echo "    - ens25f0-ens25f1 (Intel X520 10GbE)"
echo ""
echo "  Server 2 有这些RDMA网口:"
echo "    - eno3np0 (Mellanox ConnectX-5, PCIe slot 32:00.0)"
echo "    - eno4np1 (Mellanox ConnectX-5, PCIe slot 32:00.1)"
echo "  还有这些**非RDMA**网口:"
echo "    - enp177s0f0np0 (Broadcom 10GbE) ← 当前正在使用"
echo "    - eno8303/eno8403 (Broadcom 1GbE)"
echo ""
echo "请机房人员确认网线插的是 ens19f0np0/ens19f1np1 和 eno3np0/eno4np1"
echo ""

echo "===== 步骤 3: 检查光模块(SFP+/QSFP+) ====="
echo ""
echo "运行以下命令检查是否安装了光模块："
echo ""
echo "  # Server 1"
echo "  ssh sheng-xiang@10.21.16.124 'ethtool -m ens19f0np0 2>&1 || echo No transceiver'"
echo ""
echo "  # Server 2"
echo "  ssh sheng-xiang@100.64.0.6 'ethtool -m eno3np0 2>&1 || echo No transceiver'"
echo ""
echo "期望结果: 显示光模块信息（波长、功率等）"
echo "如果显示 'No transceiver present' 或类似信息 → 光模块未安装"
echo ""

echo "===== 步骤 4: 检查网线两端连接 ====="
echo ""
echo "RDMA网线必须两端都连接正确："
echo "  一端: Server 1 的 Mellanox RDMA 网卡"
echo "  另一端: Server 2 的 Mellanox RDMA 网卡"
echo ""
echo "常见问题："
echo "  1. 网线插到了Intel/Broadcom网卡（非RDMA）"
echo "  2. 网线只插了一端，另一端悬空"
echo "  3. 网线类型不对（需要用DAC/AOC/光纤，不是普通网线）"
echo ""

echo "===== 步骤 5: 尝试启用接口 ====="
echo ""
echo "即使网线插了，接口可能需要手动启用："
echo ""
echo "  # 需要root权限"
echo "  ssh sheng-xiang@10.21.16.124 'sudo ip link set ens19f0np0 up'"
echo "  ssh sheng-xiang@100.64.0.6 'sudo ip link set eno3np0 up'"
echo ""
echo "启用后再检查："
echo "  ethtool ens19f0np0 | grep Link"
echo ""

echo "===== 步骤 6: 检查RDMA链路状态 ====="
echo ""
echo "  # 查看RDMA链路是否UP"
echo "  ssh sheng-xiang@10.21.16.124 'rdma link show'"
echo "  ssh sheng-xiang@100.64.0.6 'rdma link show'"
echo ""
echo "  # 查看物理状态"
echo "  ssh sheng-xiang@10.21.16.124 'cat /sys/class/infiniband/mlx5_0/ports/1/phys_state'"
echo "  ssh sheng-xiang@100.64.0.6 'cat /sys/class/infiniband/roceo3/ports/1/phys_state'"
echo ""
echo "期望结果:"
echo "  phys_state: 5: LinkUp"
echo "  state: 4: ACTIVE"
echo ""

echo "============================================================"
echo "快速验证命令（请复制运行）"
echo "============================================================"
echo ""
echo "# 快速检查所有网口连接状态"
echo "for iface in ens19f0np0 ens19f1np1 eno3np0 eno4np1; do"
echo "  echo \"\$iface: \$(ethtool \$iface 2>/dev/null | grep 'Link detected')\""
echo "done"
echo ""
echo "# 检查光模块"
echo "ethtool -m ens19f0np0 2>&1 | head -5"
echo "ethtool -m eno3np0 2>&1 | head -5"
echo ""
echo "============================================================"
